// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// mdal_core.cpp
std::string mdal_version_();
extern "C" SEXP _rmdal_mdal_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_version_());
  END_CPP11
}
// mdal_core.cpp
int mdal_last_status_();
extern "C" SEXP _rmdal_mdal_last_status_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_last_status_());
  END_CPP11
}
// mdal_core.cpp
int mdal_driver_count_();
extern "C" SEXP _rmdal_mdal_driver_count_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_driver_count_());
  END_CPP11
}
// mdal_core.cpp
list mdal_drivers_();
extern "C" SEXP _rmdal_mdal_drivers_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_drivers_());
  END_CPP11
}
// mdal_load.cpp
sexp mdal_load_(std::string uri);
extern "C" SEXP _rmdal_mdal_load_(SEXP uri) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_load_(cpp11::as_cpp<cpp11::decay_t<std::string>>(uri)));
  END_CPP11
}
// mdal_load.cpp
int mdal_mesh_vertex_count_(sexp mesh_xptr);
extern "C" SEXP _rmdal_mdal_mesh_vertex_count_(SEXP mesh_xptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_mesh_vertex_count_(cpp11::as_cpp<cpp11::decay_t<sexp>>(mesh_xptr)));
  END_CPP11
}
// mdal_load.cpp
int mdal_mesh_face_count_(sexp mesh_xptr);
extern "C" SEXP _rmdal_mdal_mesh_face_count_(SEXP mesh_xptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_mesh_face_count_(cpp11::as_cpp<cpp11::decay_t<sexp>>(mesh_xptr)));
  END_CPP11
}
// mdal_load.cpp
std::string mdal_mesh_projection_(sexp mesh_xptr);
extern "C" SEXP _rmdal_mdal_mesh_projection_(SEXP mesh_xptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdal_mesh_projection_(cpp11::as_cpp<cpp11::decay_t<sexp>>(mesh_xptr)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rmdal_mdal_driver_count_",      (DL_FUNC) &_rmdal_mdal_driver_count_,      0},
    {"_rmdal_mdal_drivers_",           (DL_FUNC) &_rmdal_mdal_drivers_,           0},
    {"_rmdal_mdal_last_status_",       (DL_FUNC) &_rmdal_mdal_last_status_,       0},
    {"_rmdal_mdal_load_",              (DL_FUNC) &_rmdal_mdal_load_,              1},
    {"_rmdal_mdal_mesh_face_count_",   (DL_FUNC) &_rmdal_mdal_mesh_face_count_,   1},
    {"_rmdal_mdal_mesh_projection_",   (DL_FUNC) &_rmdal_mdal_mesh_projection_,   1},
    {"_rmdal_mdal_mesh_vertex_count_", (DL_FUNC) &_rmdal_mdal_mesh_vertex_count_, 1},
    {"_rmdal_mdal_version_",           (DL_FUNC) &_rmdal_mdal_version_,           0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rmdal(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
