# Generated by cpp11: do not edit by hand

mdal_version_ <- function() {
  .Call(`_rmdal_mdal_version_`)
}

mdal_last_status_ <- function() {
  .Call(`_rmdal_mdal_last_status_`)
}

mdal_driver_count_ <- function() {
  .Call(`_rmdal_mdal_driver_count_`)
}

mdal_drivers_ <- function() {
  .Call(`_rmdal_mdal_drivers_`)
}

mdal_load_ <- function(uri) {
  .Call(`_rmdal_mdal_load_`, uri)
}

mdal_mesh_vertex_count_ <- function(mesh_xptr) {
  .Call(`_rmdal_mdal_mesh_vertex_count_`, mesh_xptr)
}

mdal_mesh_face_count_ <- function(mesh_xptr) {
  .Call(`_rmdal_mdal_mesh_face_count_`, mesh_xptr)
}

mdal_mesh_edge_count_ <- function(mesh_xptr) {
  .Call(`_rmdal_mdal_mesh_edge_count_`, mesh_xptr)
}

mdal_mesh_projection_ <- function(mesh_xptr) {
  .Call(`_rmdal_mdal_mesh_projection_`, mesh_xptr)
}

mdal_mesh_driver_name_ <- function(mesh_xptr) {
  .Call(`_rmdal_mdal_mesh_driver_name_`, mesh_xptr)
}

mdal_mesh_extent_ <- function(mesh_xptr) {
  .Call(`_rmdal_mdal_mesh_extent_`, mesh_xptr)
}

mdal_mesh_dataset_group_count_ <- function(mesh_xptr) {
  .Call(`_rmdal_mdal_mesh_dataset_group_count_`, mesh_xptr)
}
